/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommandRouteImport } from './routes/command'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanetsIndexRouteImport } from './routes/planets.index'
import { Route as PlanetsPlanetIdRouteImport } from './routes/planets.$planetId'

const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsIndexRoute = PlanetsIndexRouteImport.update({
  id: '/planets/',
  path: '/planets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsPlanetIdRoute = PlanetsPlanetIdRouteImport.update({
  id: '/planets/$planetId',
  path: '/planets/$planetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/dashboard': typeof DashboardRoute
  '/missions': typeof MissionsRoute
  '/personnel': typeof PersonnelRoute
  '/planets/$planetId': typeof PlanetsPlanetIdRoute
  '/planets/': typeof PlanetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/dashboard': typeof DashboardRoute
  '/missions': typeof MissionsRoute
  '/personnel': typeof PersonnelRoute
  '/planets/$planetId': typeof PlanetsPlanetIdRoute
  '/planets': typeof PlanetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/dashboard': typeof DashboardRoute
  '/missions': typeof MissionsRoute
  '/personnel': typeof PersonnelRoute
  '/planets/$planetId': typeof PlanetsPlanetIdRoute
  '/planets/': typeof PlanetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/dashboard'
    | '/missions'
    | '/personnel'
    | '/planets/$planetId'
    | '/planets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command'
    | '/dashboard'
    | '/missions'
    | '/personnel'
    | '/planets/$planetId'
    | '/planets'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/dashboard'
    | '/missions'
    | '/personnel'
    | '/planets/$planetId'
    | '/planets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRoute
  DashboardRoute: typeof DashboardRoute
  MissionsRoute: typeof MissionsRoute
  PersonnelRoute: typeof PersonnelRoute
  PlanetsPlanetIdRoute: typeof PlanetsPlanetIdRoute
  PlanetsIndexRoute: typeof PlanetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets/': {
      id: '/planets/'
      path: '/planets'
      fullPath: '/planets/'
      preLoaderRoute: typeof PlanetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets/$planetId': {
      id: '/planets/$planetId'
      path: '/planets/$planetId'
      fullPath: '/planets/$planetId'
      preLoaderRoute: typeof PlanetsPlanetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRoute,
  DashboardRoute: DashboardRoute,
  MissionsRoute: MissionsRoute,
  PersonnelRoute: PersonnelRoute,
  PlanetsPlanetIdRoute: PlanetsPlanetIdRoute,
  PlanetsIndexRoute: PlanetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
